src/pt-xhost-local-root.conf                    /etc/lightdm/lightdm.conf.d/
src/g_ether.conf                                /etc/modprobe.d/
src/90-ptusb0.rules                             /etc/udev/rules.d/
src/70-wifi-powersave.rules                     /etc/udev/rules.d/
src/pt-rpi-eeprom-update                        /usr/bin/
src/pt-eeprom-hook                              /usr/lib/rpi-eeprom-update/
src/pt-force-rpi-eeprom-install                 /usr/lib/rpi-eeprom-update/
src/pwdptom.sh                                  /usr/lib/pt-os-mods/
