#!/bin/bash

EEPROM_CONFIG_FILE="/etc/default/rpi-eeprom-update"

if [[ "${1}" == "remove" ]]; then

  # Back up existing config file
  cp "${EEPROM_CONFIG_FILE}" "${EEPROM_CONFIG_FILE}.pt-os-mods.bak"

  # Move backed up config file back to original position
  if [[ -f "${EEPROM_CONFIG_FILE}.bak" ]]; then
    mv "${EEPROM_CONFIG_FILE}.bak" "${EEPROM_CONFIG_FILE}"
  fi

fi

systemctl unmask rpi-eeprom-update.service
systemctl enable rpi-eeprom-update.service

#DEBHELPER#
