#src/pt-user                                     /usr/bin/
#src/hotplug_display.sh                          /usr/lib/pt-os-mods/
#src/70-hotplug-resolution-ptscreen.rules        /lib/udev/rules.d/
src/70-wlan-disable-powersave.rules             /lib/udev/rules.d/
src/pt-os-mods.sh                               /usr/lib/pt-os-mods/
pkg/pwdptom.sh                                  /usr/lib/pt-os-mods/
