#!/bin/bash

# This script will force the install of the latest available Raspberry Pi
# EEPROM on the OS. This allows for patching the current version, and downgrading.

if [ -f /etc/default/rpi-eeprom-update ]; then

	# shellcheck disable=SC1091
	. /etc/default/rpi-eeprom-update

fi

FIRMWARE_ROOT=${FIRMWARE_ROOT:-/lib/firmware/raspberrypi/bootloader}
FIRMWARE_RELEASE_STATUS=${FIRMWARE_RELEASE_STATUS:-critical}
FIRMWARE_IMAGE_DIR=${FIRMWARE_IMAGE_DIR:-${FIRMWARE_ROOT}/${FIRMWARE_RELEASE_STATUS}}
EEPROM_SIZE=524288

echo "Looking up latest EEPROM file to install..."

latest=$(find "${FIRMWARE_IMAGE_DIR}" \
	-maxdepth 1 \
	-type f \
	-size "${EEPROM_SIZE}c" \
	-regex ".*/pieeprom-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].bin" |
	sort -r | head -n1)

if [[ -n "${latest}" ]]; then

	echo "Latest: ${latest}"
	echo "Running rpi-eeprom-update -f ${latest}"
	sudo rpi-eeprom-update -f "${latest}"
	exit 0

else

	echo "No latest EEPROM file found - exiting..."
	exit 1

fi
