#!/bin/bash

if [ "$EUID" -ne 0 ]; then

  echo "Please run as root"
  exit 1

fi

model="$(tr -d '\0' </proc/device-tree/model)"
echo "Model: ${model}"

if [[ "${model}" != *"Raspberry Pi 4"* ]]; then

  echo "Not Raspberry Pi 4 - exiting..."
  exit 0

fi

output="$(rpi-eeprom-update)"

bootloader_current="$(echo "${output}" | ag "CURRENT" | head -n1 | awk '{print $NF}' | sed 's/[()]//g')"
bootloader_latest="$(echo "${output}" | ag "LATEST" | head -n1 | awk '{print $NF}' | sed 's/[()]//g')"

vl805_current="$(echo "${output}" | ag "CURRENT" | tail -n1 | awk '{print $NF}')"
vl805_latest="$(echo "${output}" | ag "LATEST" | tail -n1 | awk '{print $NF}')"

echo "BOOTLOADER"
echo "CURRENT: ${bootloader_current}"
echo " LATEST: ${bootloader_latest}"

echo ""

echo "VL805"
echo "CURRENT: ${vl805_current}"
echo " LATEST: ${vl805_latest}"

FORCE_EEPROM_UPDATE="/usr/lib/rpi-eeprom-update/pt-force-rpi-eeprom-install-and-reboot"
FORCE_EEPROM_COMMAND="env SUDO_ASKPASS=/usr/lib/pt-os-mods/pwdptom.sh sudo -A ${FORCE_EEPROM_UPDATE}"
NOTIFICATION_TITLE="Invalid Raspberry Pi EEPROM configuration"

notifyUserInvalidLatestEEPROMConfig() {
  echo "Sending notification to user with request to apply patch..."

  # TODO: handle wording
  DISPLAY=:0 pt-notify-send -t 0 \
    "--action=Apply patch and reboot:${FORCE_EEPROM_COMMAND}" \
    "${NOTIFICATION_TITLE}" \
    "A patch to the Raspberry Pi EEPROM is required for full functionality."
}

notifyUserInvalidAheadOfLatestEEPROMConfig() {
  echo "Sending notification to user with request to downgrade EEPROM and apply patch..."

  # TODO: handle wording
  DISPLAY=:0 pt-notify-send -t 0 \
    "--action=Apply patch with downgrade and reboot:${FORCE_EEPROM_COMMAND}" \
    "${NOTIFICATION_TITLE}" \
    "A patch to the Raspberry Pi EEPROM is required for full functionality.
EEPROM version on Raspberry Pi is not available, so downgrade is required"
}

currentEEPROMConfigIsValid() {
  echo "No bootloader updates available - checking for valid EEPROM config"

  if [ -f /etc/default/rpi-eeprom-update ]; then
    # shellcheck disable=SC1091
    . /etc/default/rpi-eeprom-update
  fi

  echo "Config hook: ${EEPROM_CONFIG_HOOK}"

  if [ -x "${EEPROM_CONFIG_HOOK}" ]; then

    echo "Executable config hook found"

    orig_bootloader_config="$(/opt/vc/bin/vcgencmd bootloader_config)"

    mod_bootloader_config="$(echo "${orig_bootloader_config}" | ${EEPROM_CONFIG_HOOK})"

    if [[ "${mod_bootloader_config}" == "${orig_bootloader_config}" ]]; then

      echo "Raspberry Pi bootloader configuration is correct for current pi-top device"
      echo "No action required..."

      return 0

    else

      echo "Raspberry Pi bootloader configuration is incorrect for current pi-top device"

      echo
      diff --color='always' --suppress-common-lines <(echo "${orig_bootloader_config}") <(echo "${mod_bootloader_config}")
      echo

      return 1

    fi

  else

    echo "No executable config hook found."

  fi

  return 0
}

if [[ "${vl805_current}" -lt "${vl805_latest}" ]]; then

  echo "VL805 firmware update available - running 'rpi-eeprom-update -A vl805'..."
  rpi-eeprom-update -A vl805

else

  echo "No VL805 firmware update available"

fi

if [[ "${bootloader_current}" -lt "${bootloader_latest}" ]]; then

  echo "Bootloader firmware update available - running 'rpi-eeprom-update -A bootloader'..."
  rpi-eeprom-update -A bootloader

  if ! currentEEPROMConfigIsValid; then
    echo "Rebooting to apply update..."
    reboot
  fi

elif [[ "${bootloader_current}" -gt "${bootloader_latest}" ]]; then

  echo "Raspberry Pi version is ahead of latest on OS."

  if ! currentEEPROMConfigIsValid; then

    if [[ "$(/usr/bin/pt-host)" != "pi-top [4]" ]]; then

      notifyUserInvalidAheadOfLatestEEPROMConfig

    else

      ${FORCE_EEPROM_COMMAND}

    fi

  fi

  exit 0

else

  if ! currentEEPROMConfigIsValid; then

    if [[ "$(/usr/bin/pt-host)" != "pi-top [4]" ]]; then

      notifyUserInvalidLatestEEPROMConfig

    else

      ${FORCE_EEPROM_COMMAND}

    fi

  fi

  exit 0

fi
