#!/bin/bash

model="$(cat /proc/device-tree/model)"
echo "Model: ${model}"

if [[ "${model}" != *"Raspberry Pi 4"* ]]; then
  echo "Not Raspberry Pi 4 - exiting..."
  return 0
fi

if [[ "$(/usr/bin/pt-host)" != "pi-top [4]" ]]; then
  echo "No pi-top [4] detected - exiting..."
  return 0
fi

output="$(rpi-eeprom-update)"

bootloader_current="$(echo "${output}" | ag "CURRENT" | head -n1)"
bootloader_latest="$(echo "${output}" | ag "LATEST" | head -n1)"

vl805_current="$(echo "${output}" | ag "CURRENT" | tail -n1)"
vl805_latest="$(echo "${output}" | ag "LATEST" | tail -n1)"

# TODO: what if latest is older than current?
if [[ "${bootloader_current}" == "${bootloader_latest}" ]] && [[ "${vl805_current}" == "${vl805_latest}" ]]; then

  echo "No firmware updates available - checking for valid EEPROM config"

  if [ -f /etc/default/rpi-eeprom-update ]; then
    # shellcheck disable=SC1091
    . /etc/default/rpi-eeprom-update
  fi

  if [ -x "${EEPROM_CONFIG_HOOK}" ]; then

    orig_bootloader_config="$(/opt/vc/bin/vcgencmd bootloader_config)"
    mod_bootloader_config="$(echo "${orig_bootloader_config}" | ${EEPROM_CONFIG_HOOK})"

    if [[ "${mod_bootloader_config}" == "${orig_bootloader_config}" ]]; then

      echo "Raspberry Pi bootloader configuration is correct for current pi-top device"

    else

      echo "Raspberry Pi bootloader configuration is incorrect for current pi-top device"

      # TODO: create script to actually apply patch
      # NOTE: user could have newer bootloader than latest on OS
      # (see 'what if latest is older than current?')

      pt-notify-send -t 0 \
        "--action=Apply and reboot:/bin/false" \
        "--action=Ask me next time:/bin/false" \
        "Invalid Raspberry Pi EEPROM configuration" \
        "A patch to the Raspberry Pi EEPROM is required for full functionality."
    fi
  fi

else

  echo "Firmware updates available - running rpi-eeprom-update"
  rpi-eeprom-update -a

fi
