#!/bin/bash

pi_cfg="/home/pi/.config"
xdg_sys="/etc/xdg"
usr_shr="/usr/share"
lxde_usr="LXDE-pt"

sys_lxpanel_file="$xdg_sys/lxpanel/default/panels/panel"
sys_gtk_file="$usr_shr/pt-ui-overrides/gtk.css"
sys_lxsession_file="$xdg_sys/lxsession/$lxde_usr/desktop.conf"
sys_pcmanfm_file="$xdg_sys/pcmanfm/$lxde_usr/desktop-items-0.conf"
sys_lxterminal_file="$usr_shr/lxterminal/lxterminal.conf"

pi_lxpanel_file="$pi_cfg/lxpanel/$lxde_usr/panels/panel"
pi_gtk_file="$pi_cfg/gtk-3.0/gtk.css"
pi_lxsession_file="$pi_cfg/lxsession/$lxde_usr/desktop.conf"
pi_pcmanfm_file="$pi_cfg/pcmanfm/$lxde_usr/desktop-items-0.conf"
pi_lxterminal_file="$pi_cfg/lxterminal/lxterminal.conf"


main() {
    echo "Configuring display for screen size"
    determine_display_sizes_from_screen
    configure_screen_system "$menu_height" "$font_size" "$terminal_font_size"
    configure_screen_pi "$menu_height" "$font_size" "$terminal_font_size"

}

display_var_is_set() {
    if [ ! -z "$DISPLAY" ]; then
        return 0
    else
        return 1
    fi
}

determine_display_sizes_from_screen() {
    dimensions_w_quotes="$(fbset -s | grep "mode " | cut -d' ' -f2)"
    dimensions_wo_suffix="${dimensions_w_quotes%\"}"
    dimensions="${dimensions_wo_suffix#\"}"
    width="$(echo "$dimensions" | cut -d'x' -f1)"
    height="$(echo "$dimensions" | cut -d'x' -f2)"

    echo "Width: $width, height: $height"
    if [[ "$width" == "1366" ]] && [[ "$height" == "768" ]]; then
        echo "Valid screen resolution"
        menu_height=36; font_size=12; terminal_font_size=10
    elif [[ "$width" == "1920" ]] && [[ "$height" == "1080" ]]; then
        echo "Valid screen resolution"
        menu_height=48; font_size=16; terminal_font_size=13
    else
        echo "Invalid screen resolution"
        exit 1
    fi
}

change_value_in_file() {
    line_str_to_find="$1"
    file_path="$2"
    separator="$3"
    new_value="$4"
    line=$(grep "$line_str_to_find" "$file_path" || printf "")
    if [[ "$line" == "" ]]; then
        echo "Unable to find '$line_str_to_find' in $file_path"
        return 1
    else
        old_value="$(echo "$line" | awk -F "$separator" '{print $NF}')"

        new_line="${line/$old_value/$new_value}"
        sed -i "s|.*$line_str_to_find.*|$new_line|g" "$file_path"
        return 0
    fi
}

change_size_in_file() {
    line_str_to_find="$1"
    file_path="$2"
    new_value="$3"
    separator="="
    change_value_in_file "$line_str_to_find" "$file_path" "$separator" "$new_value"
    return $?
}

change_fontsize_in_file() {
    line_str_to_find="$1"
    file_path="$2"
    new_value="$3"
    separator=" "
    change_value_in_file "$line_str_to_find" "$file_path" "$separator" "$new_value"
    return $?
}

configure_screen_system() {
    echo "Configuring system configuration files... menu height: $menu_height, font size: $font_size"

    # Set menu size - system
    change_size_in_file "height=" "$sys_lxpanel_file" "$1" || true
#    change_size_in_file "iconsize=" "$sys_lxpanel_file" "$1"  # User config setting for icon size not retrieved from this file

    # Set font size - system
    change_fontsize_in_file "font-size:" "$sys_gtk_file" "$2" || true
    change_fontsize_in_file "sGtk/FontName=" "$sys_lxsession_file" "$2" || true
    change_fontsize_in_file "desktop_font=" "$sys_pcmanfm_file" "$2" || true

    # Set terminal font size - system
    change_fontsize_in_file "fontname=" "$sys_lxterminal_file" "$3" || true
}

configure_screen_pi() {
    echo "Configuring pi user's configuration files... menu height: $menu_height, font size: $font_size"

    # Set menu size - user
    if [[ -f "$pi_lxpanel_file" ]]; then
        change_size_in_file "height=" "$pi_lxpanel_file" "$1"
        height_changed=$?
        change_size_in_file "iconsize=" "$pi_lxpanel_file" "$1"
        iconsize_changed=$?
        if ( height_changed || iconsize_changed ) && display_var_is_set; then
            echo "lxpanel configuration changed - refreshing"
            lxpanelctl restart
        fi
    fi
    # Set font size - user
    if [[ -f "$pi_gtk_file" ]]; then
        change_fontsize_in_file "font-size:" "$pi_gtk_file" "$2"
    fi
    if [[ -f "$pi_lxsession_file" ]]; then
        change_fontsize_in_file "sGtk/FontName=" "$pi_lxsession_file" "$2"
        # if change_fontsize_in_file "sGtk/FontName=" "$pi_lxsession_file" "$2" && display_var_is_set; then
        #     echo "lxsession configuration changed - refreshing"
        #     su - pi -c "DISPLAY=:0 lxsession --reload &"
        # fi
    fi
    if [[ -f "$pi_pcmanfm_file" ]]; then
        if change_fontsize_in_file "desktop_font=" "$pi_pcmanfm_file" "$2" && display_var_is_set; then
            echo "pcmanfm configuration changed - refreshing"
            su - pi -c "DISPLAY=:0 pcmanfm --reconfigure"
        fi
    fi
    if [[ -f "$pi_lxterminal_file" ]]; then
        # Set terminal font size - user
        change_fontsize_in_file "fontname=" "$pi_lxterminal_file" "$3"
    else
        echo "No user lxterminal file - skipping"
    fi

    echo "Done configuring"
}

main
